name: Release

on:
  # release:
  #   types: [published, edited]
  # workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #     - master
  #   paths:
  #     - '**/*.go'
  #     - '.github/workflows/release.yml'

  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.21.6'

      - name: Run build project
        run: |
          cd $GITHUB_WORKSPACE/cmd
          go mod tidy
          mkdir build
          export PROJECT_NAME=$(basename $RUNNER_WORKSPACE)
          export GOARCH=amd64
          export CGO_ENABLED=0

          export GOOS=linux
          export GOARCH=amd64
          go build -o "${GITHUB_WORKSPACE}/build/${PROJECT_NAME}"

          export GOOS=windows
          export GOARCH=amd64
          go build -o "${GITHUB_WORKSPACE}/build/${PROJECT_NAME}64.exe"

          export GOOS=windows
          export GOARCH=386
          go build -o "${GITHUB_WORKSPACE}/build/${PROJECT_NAME}32.exe"

          ls -aln ${GITHUB_WORKSPACE}/build/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        id: upload-release-asset 
        run: |
          echo ${PROJECT_NAME}
          ls -aln ${GITHUB_WORKSPACE}/build/

          
        # uses: actions/upload-release-asset@v1
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
        #   upload_url: ${{ steps.create_release.outputs.upload_url }}
        #   asset_path: ./my-artifact.zip
        #   asset_name: my-artifact.zip
        #   asset_content_type: application/zip
