name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - '**/*.go'
      - '.github/workflows/release.yml'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run build project
        run: |
          cd $GITHUB_WORKSPACE
          echo $(ls -aln .)
          # apt-get update
          # apt-get install go
          # go mod tidy
          echo
          echo
          echo $(env)
