name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - '**/*.go'
      - '.github/workflows/release.yml'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.21.6'

      - name: Run build project
        run: |
          cd $GITHUB_WORKSPACE/cmd
          go mod tidy
          mkdir build
          export PROJECT_NAME=$(basename $RUNNER_WORKSPACE)
          export GOARCH=amd64
          export CGO_ENABLED=0

          export GOOS=linux
          export GOARCH=amd64
          go build -o "${GITHUB_WORKSPACE}/build/${PROJECT_NAME}"

          export GOOS=windows
          export GOARCH=amd64
          go build -o "${GITHUB_WORKSPACE}/build/${PROJECT_NAME}64.exe"

          export GOOS=windows
          export GOARCH=386
          go build -o "${GITHUB_WORKSPACE}/build/${PROJECT_NAME}32.exe"

          ls -aln ${GITHUB_WORKSPACE}/build/
