name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - '**/*.go'
      - '.github/workflows/release.yml'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.21.6'
      - run: go version

      - name: Run build project
        run: |
          go env
          echo
          cd $GITHUB_WORKSPACE
          echo $(ls -aln .)
          # apt-get update
          # apt-get install go
          # go mod tidy
          echo
          echo
          echo $(env)
